name: weather_app
description: A new Flutter project.
# Следующая строка предотвращает случайную публикацию пакета в pub.dev с помощью `flutter pub publish`
publish_to: 'none' # Можно удалить эту строку, если захотите опубликовать в pub.dev

# Ниже указаны версия и номер сборки для вашего приложения. 
# Номер версии - это три цифры, разделенные точками, например 1.2.43, за которыми следует необязательный номер сборки,
# разделенный знаком +. Как версия, так и номер сборки могут быть 
# переопределены в сборке flutter, указав --build-name и --build-number соответственно.
# В Android имя сборки используется как имя версии,
# в то время как номер сборки используется как код версии.
# Подробнее об управлении версиями Android https://developer.android.com/studio/publish/versioning
# В iOS имя сборки используется как CFBundleShortVersionString, в то время как номер сборки используется как CFBundleVersion.
# Подробнее об управлении версиями iOS
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# В Windows название сборки используется в качестве основной, второстепенной части и исправления версий продукта и файла,
# в то время как номер сборки используется в качестве суффикса сборки.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Зависимости определяют другие пакеты, которые необходимы пакету для работы. 
# Чтобы автоматически обновить зависимости пакета до последнией версии, нужно запустить "обновление flutter pub --основные версии".
# В качестве альтернативы зависимости можно обновить вручную, изменив приведенные ниже 
# номера версий на последнюю версию, доступную на pub.dev. 
# Чтобы увидеть, в каких зависимостях доступны более новые версии, запустите "flutter pub устарел".
dependencies:
  flutter:
    sdk: flutter
  searchfield: ^0.7.5
  open_weather_client: ^2.2.0
  simple_autocomplete_search: ^1.0.5
  weather:
  open_weather_widget: ^0.0.3





  # Добавляет шрифт Cupertino Icons в приложение.
  # Использовать с классом CupertinoIcons для иконок в стиле iOS.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Приведенный ниже пакет "flutter_lints" содержит набор рекомендуемых строк
  # для поощрения надлежащей практики кодирования. Набор lint, предоставляемый пакетом, активируется в файле `analysis_options.yaml`,
  # расположенном в корневом каталоге пакета. Смотрите этот файл для получения информации
  # об отключении определенных правил удаления lint и активации дополнительных правил.
  flutter_lints: ^2.0.0

# Для получения информации об общей части Dart этого файла 
# https://dart.dev/tools/pub/pubspec

# Следующий раздел посвящен пакетам Flutter
flutter:

  # Следующая строка гарантирует, что шрифт Material Icons
  # включен в приложение, так что вы можно 
  # использовать значки в классе material Icons.
  uses-material-design: true

  # Чтобы добавить assets в приложение нужно добавить раздел assets
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # Ресурс изображения может относиться к одному или нескольким "вариантам"
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Информация о добавлении ресурсов из зависимостей пакетов
  # https://flutter.dev/assets-and-images/#from-packages

  # Чтобы добавить пользовательские шрифты в приложение, добавьте раздел "шрифты",
  # в разделе "flutter". Каждая запись в этом списке должна иметь ключ "family" 
  # с названием семейства шрифтов и ключ "fonts" со списком,
  #  содержащим ресурс и другие дескрипторы для шрифта.
  # Например:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Информация о шрифтах из зависимостей пакетов 
  # https://flutter.dev/custom-fonts/#from-packages
